AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DomainName:
    Type: String
    Description: Parameter DomainName
Resources:
  dnsEntry:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref 'HostedZone'
      RecordSets:
        - Name: !Sub '${AWS::StackName}.${DomainName}'
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt 'www.DomainName'
  www:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub '${AWS::StackName}.${DomainName}'
        Origins:
          - Id: api
            DomainName: !Sub '${dataApi}.execute-api.${AWS::Region}.amazonaws.com'
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: match-viewer
          - Id: S3Origin
            DomainName: !Sub '${wwwBucket}.s3-website-${AWS::Region}.amazonaws.com'
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
        Enabled: true
        Comment: API access
        PriceClass: PriceClass_100
        CacheBehaviors:
          - PathPattern: api/*
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            CachedMethods:
              - GET
              - HEAD
              - OPTIONS
            ForwardedValues:
              QueryString: true
              Headers:
                - Authorization
                - Origin
              Cookies:
                Forward: none
            MinTTL: '0'
            DefaultTTL: '0'
            MaxTTL: '0'
            TargetOriginId: api
            ViewerProtocolPolicy: https-only
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: true
            Headers:
              - Authorization
              - Origin
            Cookies:
              Forward: none
          MinTTL: '0'
          DefaultTTL: '0'
          MaxTTL: '0'
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
  wwwBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Sub '${AWS::StackName}.glycocode.com'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
        RoutingRules:
          - RedirectRule:
              ReplaceKeyWith: doi/cleaneddoi
            RoutingRuleCondition:
              KeyPrefixEquals: doi/unclean/doi/
  wwwBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'wwwBucket'
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${wwwBucket}/*'
            Principal: '*'
