AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    parentstackName:
      Type: String
      Description: 'Parent stack name'
Resources:
  CopyDatasetsTestRunReadOnlyPermissions:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: 'Permissions to run test runs for copying datasets to deploy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: CopyDatasetsRead
            Effect: Allow
            Action:
              - 's3:GetObject'
            Resource:
              - !<!Sub> 'arn:aws:s3:::${parentstackName}-gator/uploads/*'
          - Sid: CopyDatasetsReadOnly
            Effect: Deny
            Action:
              - 's3:PutObject'
              - 's3:DeleteObject'
            Resource:
              - !<!Sub> 'arn:aws:s3:::${parentstackName}-gator/uploads/*'
          - Sid: ListDatasets
            Effect: Allow
            Action:
              - 's3:ListBucket'
            Resource:
              - !<!Sub> 'arn:aws:s3:::${parentstackName}-gator'
            Condition:
              StringEquals:
                's3:prefix': uploads/

Outputs: {}