#!/usr/bin/python3

import csv
import sys
import os.path
import json
import re
import subprocess

all_roles = {}

stack = sys.argv[1]
wanted_role = sys.argv[2]

resources_file = f"{stack}-resources.conf.json"

if os.path.isfile(resources_file):
  with open(resources_file) as f:
    all_resource_data = json.load(f)
    resource_data = all_resource_data['policies']
    region = all_resource_data['region']

def convert_policy(policy,policyarns):
  if policy in policyarns:
    return(policyarns[policy])

  return(re.sub(r'policy/.*', policy, next(iter(policyarns.values())) ))

with open("vault_roles.tsv") as tsvfile:
  tsvreader = csv.reader(tsvfile, delimiter="\t")
  for line in tsvreader:
    all_roles[line[0]] = [ convert_policy(policy,resource_data) for policy in line[1].split(',')]

policy_string = ','.join(all_roles[wanted_role])
print(policy_string, region,wanted_role)
add_role = subprocess.run(["./scripts/setup_vault", "-r", region, f'gator-{stack}', wanted_role, policy_string ])
if add_role.returncode == 0:
  print(f"Successfully created role {wanted_role} in {stack}")
else:
  print("The exit code was: %d" % add_role.returncode)