#!/bin/bash

bucket="$1"

outputdir="dist"

rm -rf "$outputdir"
mkdir "$outputdir"

./scripts/build_lambdas
# S3Bucket S3Key  Resources -> lookup function by name -> Properties -> Code , remove ZipFile, add S3Bucket S3Key
main_template_file=$(./node_modules/.bin/createstack --name Glycodomain --outputdir "$outputdir")